apiVersion: networking.k8s.io/v1
kind: Ingress
controller:
  ingressClass: "nginx"
metadata:
  name: example-ingress
  namespace: example-app
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Remplacez cela par la classe d'ingress appropriée
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example-service.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-service
            port:
              number: 80  # Assurez-vous que le numéro du port correspond à celui de votre service
