kubectlapiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: app-test.com
    http:
      paths:
      - backend:
          service:
            name: example-service
            port: 
              number: 5000
        path: /my-app
        pathType: Exact
